version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - '5444:5432'
    volumes:
      - /data/postgres:/data/postgres
    env_file:
      - docker.env
    networks:
      - postgres

  # TODO: For feature (It isn't working now)
  # frontend: 
  #   container_name: frontend
  #   build: 
  #     context: .
  #     dockerfile: ./configs/docker/frontend/Dockerfile
  #   ports:
  #     - '4000:80'

networks:
  postgres:
    driver: bridge
