services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - '5432:5432'
    volumes:
      - /data/postgres:/data/postgres
    environment:
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'admin'
      POSTGRES_DB: 'gym-mate'
    networks:
      - internal
    expose:
      - '5432'

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: ./apps/backend/Dockerfile
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: 'postgresql://admin:admin@postgres:5432/gym-mate?schema=public'
    depends_on:
      - postgres
    networks:
      - internal
    restart: always

  telegram-bot:
    container_name: telegram-bot
    build:
      context: .
      dockerfile: ./apps/telegram-bot/Dockerfile
    environment:
      BACKEND_URL: 'http://backend:3000'
    depends_on:
      - backend

    networks:
      - internal

  prisma-studio:
    container_name: prisma-studio
    build:
      context: .
      dockerfile: ./configs/docker/prisma-studio/Dockerfile
    depends_on:
      - backend
    ports:
      - '5555:5555'
    networks:
      - internal

networks:
  internal:
    driver: bridge
