services:
  watchtower:
    image: containrrr/watchtower
    command:
      - '--label-enable'
      - '--interval'
      - '30'
      - '--rolling-restart'
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - '5432:5432'
    volumes:
      - /data/postgres:/data/postgres
    environment:
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'admin'
      POSTGRES_DB: 'gym-mate'
    networks:
      - internal
    expose:
      - '5432'

  prisma-studio:
    container_name: prisma-studio
    image: timothyjmiller/prisma-studio:latest
    restart: unless-stopped
    environment:
      POSTGRES_URL: 'postgresql://admin:admin@postgres:5432/gym-mate?schema=public'
    ports:
      - 5555:5555
    depends_on:
      - postgres
    networks:
      - internal

  backend:
    container_name: gym-mate-backend
    image: ghcr.io/beer-building/gym-mate/backend:prod
    labels:
      - 'com.centurylinklabs.watchtower.enable=true'
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: 'postgresql://admin:admin@postgres:5432/gym-mate?schema=public'
    depends_on:
      - postgres
    networks:
      - internal
    restart: always

  telegram-bot:
    container_name: gym-mate-bot
    image: ghcr.io/beer-building/gym-mate/telegram-bot:prod
    labels:
      - 'com.centurylinklabs.watchtower.enable=true'
    environment:
      BACKEND_URL: 'http://backend:3000'
      DATABASE_URL: 'postgresql://admin:admin@postgres:5432/gym-mate?schema=public'
    depends_on:
      - backend
    networks:
      - internal

networks:
  internal:
    driver: bridge
