name: Code check
on: push
jobs:
  build:
    name: Code check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.10.0

      # pnpm frontend:build needs for compile svelte-kit tsconfig
      - name: Install dependencies
        run: |
          npm install -g pnpm
          pnpm install
          pnpm frontend:build

      - name: Run typescript check
        run: pnpm run lint:ts

      - name: Run Elsint
        run: pnpm run lint
