name: Lint Code Base
on: push
jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: |
          npm install -g pnpm@7.27.1
          pnpm install

      - name: Run lint
        run: pnpm run lint
