name: Check
on: push
jobs:
  build:
    name: Tslint
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.10.0

      # pnpm frontend:build needs for compile svelte-kit tsconfig
      - name: Install dependencies
        run: |
          npm install -g pnpm
          pnpm install
          pnpm frontend:build

      - name: Run ts check
        run: pnpm run lint:ts
